apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAnrM6jcaahSkMHBd4yADuXZshKmUV5YJ/V3FOWMyBxOdzSvKj/DOW0n6Y+4Vu+OnG4RJhKy4rVXDb+xylwYgsIdXhFiR1gsXyqslOI0rU/DjKjnH/+CycXFV6dgpdPFv9i3QAhq4bXkreEQFwRgANrFd7BP9FN5Rja0rwDEbVpyVkNYW7pb2z0e3twch6V/HgwzdpxZ3qbdYTpaPNsq1jkFXMJMuGDK0xVK6AYK0cRHYtBBchLc/yXAEwm8Czr+i0ETk2pNSiVMoYWUstOY3AZ8C9JGmMK8BJZ1Q1Zzqeznhnz4mmv76dQemYxCIOx5/o81FhssUb+i6TvuRmCaa2vPPems40du61g1ZnVHv5xYzjTs8S+pjuac1u0gTlVq5a5htL4Y8bMaWQqxkOyZsixnZ2mbJ8XkEAMaqvms7Sv6QK4aiSIu9mB2h151trl6KPlqaK9AWQkkSjfZnx2US6Q0wLl4+0IV9r3lOx/I75I4SddF2ZS34I3eJrxGwBJWhxEXUbFUJqILHOR4LDzagp8ESRACWv+5xwVcdIipr1txLYjms34qtePG4yxEigS2g8C5aAHCUJh02B58p/Vpa5YaOljacxc9Bed+WoCs+e5GkAFg3DaRsgUXzyTFRGxxBoy7JqYV/xtvHB3axIyOdhAk4dxWEODdl1nMsTCuDyLQRaR6+HX3jyPYkgFULBoUvrFdBkeypTp0dE7//ACXMR+oWh9fg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
