apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDqiG/gmmz3R8RhCvrzC69x1mUpXml13aUCeU/3JvfvRRyJ0Vnk7xwyvsDGj+XenGdAMlxpXj6wsiMPXQAQcnWCqhWODqdc4GAOXplkFHgebEiG0wquV2ehj1m3lat7/zTd7rXWw9Ahr0EKdrXgTfggSxqFFBPmVc/Muqn07Xfhpb2bVmBw40MjZcyQo6nBCLJhaoNnWjZLpEWQ6X2uuYSv9rKWIIAOwNps3E2gqo7/g97cEjOjq1A4fzKC5HVkO2lQ3yOFafRiY+TarEpo+UosUd2zwTj8OdjKJ94cHifOEhIMTcbWQiHL5BIdt90gbustHexmeHejCYTMS0p9/zcUc+oc6+In51UZZ9VVCcIT7+9PJAvA4Oil7+UNp6aTSFL9pQtcOB/H8NOa/6GH8LZCrE6WX1THIIDf4jABxP/t7ETqrcz1eKp3k7fR/hVbWbU4jGwUesCOEVNQ1VnSP8B1Pt1uweXy6ZBGlyYm5XAR7e7jfUkx0/YSBWVe2ALd2SkZcaAQC8O1cbgl2o+vAt1kST69e6rRMlnknTnklmOhPPvPOVRJqB5TIR+qRmBCx56oJ9yvkGx4atjcEAxosf4GkA0SRCD7qNOX6KSylsUDe/afSDrmXrWYe8LpfDqv63L2dGy3CNvveSxe+vRM4LkhFA/sczR1hG5Ty987SnesS/D3HsgEX5y0TbD0fO4oQ36XYXcRZzcdBdTJpnUwpFxyXwQfmQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
